{STEER_MOTOR_GEAR_RATIO: 15.428, DRIVE_MOTOR_GEAR_RATIO: 7.13, ENCODER_RESOLUTION: 2048.0,
  STEER_ENCODER_METERS_PER_PULSE: 0.011393651153746435, DRIVE_FEEDFORWARD_KS: 0.01,
  DRIVE_FEEDFORWARD_KV: 0.5, STEER_FEEDFORWARD_KS: 0.0, STEER_FEEDFORWARD_KV: 0.01,
  WHEEL_RADIUS_METERS: 0.415, TRACK_WIDTH_METERS: 0.6, LOOP_PERIOD_SECONDS: 0.02,
  DRIVE_P: 0.75, DRIVE_I: 0.0, DRIVE_D: 0.0, STEER_P: 1.0, STEER_I: 0.0, STEER_D: 0.0,
  FRONT_LEFT_DRIVE_MOTOR_ID: 0, FRONT_LEFT_STEER_MOTOR_ID: 1, FRONT_RIGHT_DRIVE_MOTOR_ID: 2,
  FRONT_RIGHT_STEER_MOTOR_ID: 3, BACK_LEFT_DRIVE_MOTOR_ID: 4, BACK_LEFT_STEER_MOTOR_ID: 5,
  BACK_RIGHT_DRIVE_MOTOR_ID: 6, BACK_RIGHT_STEER_MOTOR_ID: 7, FRONT_LEFT_DRIVE_INVERTED: false,
  FRONT_LEFT_STEER_INVERTED: false, FRONT_RIGHT_DRIVE_INVERTED: true, FRONT_RIGHT_STEER_INVERTED: false,
  BACK_LEFT_DRIVE_INVERTED: true, BACK_LEFT_STEER_INVERTED: false, BACK_RIGHT_DRIVE_INVERTED: false,
  BACK_RIGHT_STEER_INVERTED: false, MAX_SPEED_METERS_PER_SECOND: 2.0, MAX_ROTATION_RADIANS_PER_SECOND: 3.14159}
